name: backend-ci
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [ "recipe-service", "user-service" ]
    steps:
      - uses: actions/checkout@v4

      - name: Cache Maven repo
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: maven-

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Build (skip tests)
        working-directory: ${{ matrix.service }}
        run: mvn -q -DskipTests -DfinalName=app package

      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Docker login to ACR
        run: az acr login --name ${{ vars.ACR_NAME }}

      - name: Build & push image
        run: |
          IMAGE=${{ vars.ACR_NAME }}.azurecr.io/${{ matrix.service }}:${{ github.sha }}
          echo "Building $IMAGE"
          docker build -t $IMAGE ${{ matrix.service }}
          docker push $IMAGE

      - name: Trivy scan (fail on HIGH/CRITICAL)
        uses: aquasecurity/trivy-action@0.32.0
        with:
          image-ref: ${{ vars.ACR_NAME }}.azurecr.io/${{ matrix.service }}:${{ github.sha }}
          severity: 'HIGH,CRITICAL'
          exit-code: '1'
